export default {
    defaultPortrait: require("images/portrait.png"),
    vipIcon: require("images/vip.png"),
    close: require("images/close.png"),
    show: require("images/show.png"),
    hide: require("images/hide.png"),
    line: require("images/line.png"),
    search: require("images/search.png"),
    invite: require("images/invite.png"),
    right: require("images/right.png"),
    left: require("images/left.png"),
    bg: require("images/bg.png"),
    message: require("images/message.png"),
    radius: require("images/radius.png"),
    jugan: require("images/jugan.png"),
    mudan: require("images/mudan.png"),
    tiantangniao: require("images/tiantangniao.png"),
    mulan: require("images/mulan.png"),
    invitationcode: require("images/invitationcode.png"),
    garden: require("images/garden.png"),
    award: require("images/award.png")
};
